version: '2.3'
services:
  experiment:
    runtime: nvidia
    volumes:
      - ..:/app
    build:
      context: .
      dockerfile: gpu.Dockerfile
    image: tanimu/partialconv
    container_name: experiment

